uint32 id		#通道id
uint8 navigation_mode  # 导航模式 0： 模糊避让导航 1：精准避让导航 2：停等导航 3：等待避让导航，等待一定时间之后，再执行避让
float32 waiting_timeout # 导航模式为3时（等待避让），时间必须大于0
float32 max_speed       #最大的导航速度
bool permitted_passage  #允许通行，路径变更之后，是否允许通行，如果允许则可以按照新的路径行走，否则不允许沿变更路径行走
uint32 capacity		#通道车量
uint32 nav_dir          # 导航方向 0： 默认底层自主决定导航方向，1： 前进导航，2：后退导航, 3: 沿着路经方向走（路经在前面就前进导航，路经在后面就是后退导航）
---
int32 result            # 1: 成功，0：失败
---
geometry_msgs/PoseStamped base_position
