uint8 mode
uint8 execute_mode

#mode
uint8 CANCEL = 0
uint8 EXCUTE = 1
uint8 PAUSE = 2
uint8 RESUM = 3

#executeMode
uint8 LOCK = 1
uint8 UNLOCK = 2
---
int8 result #1表示执行成功，负值表示执行失败
uint8 execute_mode
---
int8 feedback
uint8 execute_mode
