uint8    task_type
uint8    FETCHING = 0               #取物料
uint8    FEEDING = 1                #喂料
uint8    RESETING = 2               #回到初始位置

uint8    excute_type
uint8    CANCEL = 0
uint8    EXCUTE = 1
uint8    PAUSE = 2
uint8    RESUM = 3

string   task_name                     #机械臂执行的任务名称 用于区分任务
---
uint64   status_code #状态码
uint8    result
uint8    CANCLE = 1
uint8    SUCCESS = 2
uint8    FAILED = 3
---
int8 feedback #4暂停 5继续
uint8 excute_type
uint64   status_code #状态码
