bool get_scan_match  #true : get; false: save/update scan match
geometry_msgs/PoseStamped match_pose
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
#/** 1 if the result is valid */
int32 valid
#/** Scan matching result (x,y,theta) */
float32[] x
#/** Number of iterations done */
int32 iterations
#/** Number of valid correspondence in the end */
int32 nvalid
#/** Total correspondence error */
float32 error

