# map_merge

# true: call startServe() to start map merge merge maps
# false: call stopServe() to stop map merge
bool start_map_merge

geometry_msgs/Pose initial_pose

nav_msgs/OccupancyGrid map
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
