# map_server

# true: call startServe() to start map server pub static map
# false: call stopServe() to stop publisher of map server
bool start_map_server

# Only for startMapServer == true. Leave empty for startMapServer == false
# use pathName to find .yaml
# pathName format can be [/abc/ddd/]filename[.yaml]
# if pathName == "", use last loaded pathName in map_server or failed
string path_name
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
